### ISSUE TITLE
CAST Software Member Spotlight Webinar (May 2024)

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/community_wg#104]
https://docs.google.com/document/d/15LVBNeRu1jyUyNOm5TVxDo6CZaCU0GiE/edit?usp=sharing&ouid=102812099925850911550&rtpof=true&sd=true

NEXT STEPS

- [ ] CAST to confirm presenters and share details (name, title, head shot and bio) 
- [ ] Namrata to send marketing plan for promo 
- [ ] CAST/GSF to finalize set up (will likely be organized by CAST)  
- [ ] Namrata to build stand-alone newsletter for gsf subscribers 
- [ ] @Jenya-design to develop assets for social media and newsletter 
- [ ] Namrata to promote on social media 
- [ ] Develop presentation deck
- [ ] Finalize presentation deck

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please let me know the details for this task if you need design assets ready. Thank you

**Comment by russelltrow** [comment]
Hey @NAMRATA-WOKE is this session still going ahead?

**Comment by seanmcilroy29** [comment]
@NAMRATA-WOKE - Cast Case Study Slides added
[CAST case study - using SCI and software intelligence to estimate CO2 emissions.pdf](https://github.com/Green-Software-Foundation/sci-guide/files/14721312/CAST.case.study.-.using.SCI.and.software.intelligence.to.estimate.CO2.emissions.pdf)
