### ISSUE TITLE
Project governance

### ISSUE THREAD

**Issue by caradelia** [Green-Software-Foundation/community_wg#105]
Hello,I am not easily finding your project governance. Could you point me in the right direction? Thanks!

**Comment by russelltrow** [comment]
Hello @caradelia thank you so much for your interest. You can find further information:

* Our wiki has information about our [organisational governance model](https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/983138/Governance).
* The Oversight Committee's website has information on our [project governance](https://oc.greensoftware.foundation/project-lifecycle.html).

Russ

**Comment by russelltrow** [comment]
Hi @caradelia does the above provide the information you are seeking? Russ
