### ISSUE TITLE
[MOTION] Approve the donation of the Indeed Green Software Playbooks

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#109]
## Motion

Approve the donation of the [Indeed Green Software Playbooks](https://github.com/Green-Software-Foundation/oc/issues/78) project to the Community Working Group.

## Context

[Indeed would like to donate a green software rubric to the CWG](https://github.com/Green-Software-Foundation/community-wg/issues/97).

The project has been discussed in CWG meetings and between @moin-oss, @aecurrie and @PindyBhullar.

In the [last Community Working Group meeting](https://github.com/Green-Software-Foundation/community-wg/issues/108) the group agreed that there had been enough discussion on the issue to move forward to a formal motion approving the donation.

## References

* https://github.com/Green-Software-Foundation/community-wg/issues/97
* https://github.com/Green-Software-Foundation/oc/issues/78

## Actions

* CWG members provide any comments or objections on this issue
* Pending any unresolved objections the donation will be accepted on Friday 8th March 2024

**Comment by atg-abhishek** [comment]
Hi @russelltrow can you share the actual playbook document here from Indeed? Thanks!

**Comment by russelltrow** [comment]
Hi @atg-abhishek I don't believe that @moin-oss has shared the actual playbook with us yet.

We have a document with the current status of the project and some context here: https://docs.google.com/document/d/1yn9fpB-KIv5-x8CJDB1IsLdFrb2XMZBcggQZO6N42ho/edit#heading=h.s7ho39mvfx7e

**Comment by moin-oss** [comment]
Hi @atg-abhishek , we didn't develop any completed playbooks, only a draft of one.  I can share it here if you'd like, but unfortunately, we were not able to get past the initial phases of this effort when we came up with the idea.

**Comment by moin-oss** [comment]
Looking through what we came up with, here's a very early stages draft of a playbook for building webapps:

WebApp Guidelines Rubric

Created by Edwin Cantu last modified on Jul 24, 2023

Purpose:

The goal of this rubric is to aide developers in what steps to take/implement to make sure the WebApp created is as green as possible.

Low effort

    Semi optimized query
    Semi cache the taxing query
    Small modifications for resource allocation

These recommendations would include changes that would require minimal effort, such as reduced the allocation of resources where over-allocated.

Medium effort

    Use partitioned tables
    Partial caching mechanism implemented within WebApp
    Partial modification for resource allocation
    Partially optimized Front End
    Implement resource monitors 

These would include suggestions on changes that would not be considered minimal.  For example, determining the optimal times to run a cronjob, or using a datacenter that is cleaner.

High effort

    Query optimization 
    Memory utilization of 90% and above
    Cache frequently used calls within WebApp
    Select most appropriate language for WebApp use case
    Reserving only needed resources
    Full optimization of WebApp front end (IE Font optimization, Picture optimization, and JavaScript optimization/reduction)

Such suggestions would include changes that would require high effort on the part of product teams, such as using a language or framework that is significantly more efficient than the current one.

**Comment by russelltrow** [comment]
**@moin-oss I'm very happy to say that this motion passed without objection.** 

The Oversight Committee will now have 7 days to provide any comments or objection before final approval.

https://github.com/Green-Software-Foundation/oc/issues/81

**Comment by russelltrow** [comment]
Approved by Oversight Committee
