### ISSUE TITLE
GSF Member Showcase

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/community_wg#112]
**What:** 60-minute webinar showcasing GSF member experiences

**Why:** Increase visibility for GSF members and attract more members and adopters for our tools.

**How:** Open call for organizations interested in participating. First-come, first-served basis. Inviting 5 member orgs to share their experiences in adopting our tools/resources for software decarbonization, reasons for joining GSF, collaboration experiences, and insights on strengthening the ecosystem through different players' roles.

**NEXT STEPS**

- [x] Confirm orgs represented in showcase
- [x] Schedule planning call
- [x] [Finalize content](https://docs.google.com/document/d/1fvsAuWq_d86VxlM8xvD3qLoWlDltZczqfqkVyYBCoo0/edit?usp=sharing), outline and unifying message
- [x] Members to confirm presenters and share details (name, title, head shot and bio) 
- [x] GSF to finalize set up 
- [x] Namrata to send email notifying members and audience 
- [x] @Jenya-design to develop assets for social media and newsletter 
- [x] Namrata to promote on social media 
- [x] Develop presentation deck
- [x] Finalize presentation deck

**Comment by NAMRATA-WOKE** [comment]
@russelltrow can we get this on the agenda for the upcoming call?

**Comment by NAMRATA-WOKE** [comment]
**CONFIRMED**

1. CAST Software
2. NTT DATA
3. UBS

**Comment by NAMRATA-WOKE** [comment]
CAST Software confirmed

**Comment by Jenya-design** [comment]
@russelltrow @NAMRATA-WOKE please let me know if there's an approved info/copy I can start working with for this task
Thank you

**Comment by NAMRATA-WOKE** [comment]
Blackout Dates:
June 2
June 14
June 17- 19
June 25

**Comment by NAMRATA-WOKE** [comment]
### May 21 Call Member Showcase Meeting

Scheduling the Showcase (mid 17th of June onwards)
Outlining content
Unifying message


**CAST Software (client focused; how CAST is supporting its client business)**
- technology + methodology to help industry to decarbonize software 
- opportunity to collaborate with GSF has been to referring to standards like the SCI - brought into our first step of our methodology THEN delving into coding practices where we are applying standards related to coding practices to detect and suggest improvements to green code (eg. ISO 555) 
**- Active use case in Italy with big infrastructure management company** 
      - a new regulation for Europe which will apply to all companies (EU CSRD regulation imposing reporting on emissions on all departments of any industry + asks for a forward looking posture on measurement and depict roadmap on how to improve/where to improve emissions reductions)
      - story is the application of the SCI methodology on some candidate applications 
      - demonstrate usage of other standards to help 
      - used on overall portfolio on the enterprise level with one limit: 2-3 months they promptly found the source code // usually find a really hard time (supply chain, portfolio etc)
      - Part in AWS, Asia, Prem - from a complexity point of view, this story covers every possible scenario 
      - got real time feedback from the SWG 

**UBS (internal focused - how the UBS is helping itself)** 
- why we joined in the first place - set the scene behind the rationale
   - we have been optimizng data centers
   - partnering with one of the largest hyperscalers to migrate to the cloud
   - more to do = why we joined the GSF to optimize our tech stack
   - coincided with UBS Sustainability Guild
   - Looking at the whole DevOps cycle
- Progression over the last couple of years
   - contributed to the SCI
   - banking landscape: multiple monolithic applications running across diverse data centers and low latency aspect of our trading business 
   - SCI = standardized how we measure 
   - SCI helped us understand where all the gaps are and get key data points into key areas of our data center
- GSF has a fantastic library we can plug in to our business practices 
- Being impacted by CSRD and the EU Energy Directive 
- training; thinking about what more we can do 
- Namrata: would be great to tie in the above to move towards launching TOSS (the more you feed into the foundation, the more you get out of it) 

Tuesday - Thursday preferred for CAST
Afternoon in Europe - 2/3 pm BST preferred / 12pm okay

PRESENTER FROM CAST:
Michele Slocovich or Massimo 

PRESENTER FROM UBS:
Pindy Bhullar from UBS

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design finally heard back and it looks like the event will take place June 27, 2:00 pm - 3:00 pm BST.

Can you please create a couple of assets for Mailchimp and social media to promote the event? I need at least 2 images for social and one for Mailchimp.

All the information you need is **[here](https://docs.google.com/document/d/1fvsAuWq_d86VxlM8xvD3qLoWlDltZczqfqkVyYBCoo0/edit)**. 

@gosia-f can you please build this into our social media calendar?

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @gosia-f 
Please check the update in canva and let me know if you need any adjustments
[Social images](https://www.canva.com/design/DAGIARqvPVM/GLYPoUcx9BNMerSesKGZiw/edit?utm_content=DAGIARqvPVM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
[Mailchimp banner](https://www.canva.com/design/DAGIAWX5aaw/PnyQshouFDkPOWjH42TC5w/edit?utm_content=DAGIAWX5aaw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by Jenya-design** [comment]
Last updates according to Namrata's comments
PNG files on [GSF Drive](https://drive.google.com/drive/folders/1WMmOW7SYqj_tZxSuMZ2NVL8X9AJJqhng?usp=sharing)

- [Social images - canva](https://www.canva.com/design/DAGIARqvPVM/GLYPoUcx9BNMerSesKGZiw/edit?utm_content=DAGIARqvPVM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [Mailchimp banner 1200x600 - canva](https://www.canva.com/design/DAGIAWX5aaw/PnyQshouFDkPOWjH42TC5w/edit?utm_content=DAGIAWX5aaw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [Mailchimp banner 1200x200 - canva](https://www.canva.com/design/DAGIAWX5aaw/PnyQshouFDkPOWjH42TC5w/edit?utm_content=DAGIAWX5aaw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
