### ISSUE TITLE
[MOTION] Approve the Higher Education Engagement project proposal

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#115]
## Motion

Approve the [Higher Education Engagement project proposal](https://github.com/Green-Software-Foundation/projects/issues/83) raised by @tholewis.

## Context

@tholewis would like to start a new Community Working Group project focused on GSF's engagement with Higher Education institutions.

Originally [discussed here](https://github.com/orgs/Green-Software-Foundation/discussions/72) and then in the [Community WG meeting](https://github.com/Green-Software-Foundation/community-wg/issues/88) on 25 October 2023.

The project has since been discussed in various CWG meetings and between @tholewis and @PindyBhullar.

## References

* https://github.com/Green-Software-Foundation/projects/issues/83
* https://github.com/Green-Software-Foundation/community-wg/issues/89
* [Thoughts on University engagement (supporting Student events, providing curriculum templates)](https://github.com/orgs/Green-Software-Foundation/discussions/72)

## Actions

* CWG members provide any comments or objections on this issue
* Pending any unresolved objections the project will be approved on Wednesday 8th May 2024

**Comment by russelltrow** [comment]
@tholewis the motion passed without objection and the Higher Education Engagement project is officially approved and moves into the "Draft" status 🎉 

Next step is to provision the project.

**Comment by tholewis** [comment]
This is great news to wake up to! Excited to see how the GSF can best support and inspire educators, learners, and researchers! 🌳
