### ISSUE TITLE
Green Software Landscape - Proposal

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/community_wg#27]
A proposal to set up a Green software foundation landscape, using the open source tool from CNCF, which is commonly used by other Linux Foundation projects for a consistent way to share resources. E.g. at landscape.greensoftware.foundation

Examples:
- cncf landscape - https://landscape.cncf.io/
- Guide - https://landscape.cncf.io/guide
- TODO group landscape - 
- GitHub repo - https://github.com/todogroup/ospolandscape

Taking inspiration from the CNCF and TODO group landscapes, some potential categories-
- Members
- Certified Trainers (once the updated principles are created)
- Gsf projects by working group? Similar to the map that @Henry-WattTime  has put together
- Green tools
    - Maybe using the awesome green software repo 

An example YML config file:
https://github.com/todogroup/ospolandscape/blob/master/landscape.yml

FYI @seanmcilroy29 @jawache

**Comment by Sealjay** [comment]
@seanmcilroy29 @jawche I wasn't sure if this was a better fit for community or innovation WGs

**Comment by seanmcilroy29** [comment]
@Sealjay - I think this would be a great fit for the open source Innovation WG

**Comment by Sealjay** [comment]
Awesome, cheers @seanmcilroy29 ! Have opened over there
