### ISSUE TITLE
[Speakers] Project update

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#30]
- [ ] Ontime

  - the first group of speakers has been added to the [website](https://speakers.greensoftware.foundation/). 
  - We will add further speakers, forms, filters and workflow descriptions later on. 
  - See also: [issues](https://github.com/Green-Software-Foundation/speakers/issues), [milestones](https://github.com/Green-Software-Foundation/speakers/milestones?direction=asc&sort=due_date), [project board](https://github.com/orgs/Green-Software-Foundation/projects/2/views/2).

**Comment by holanita** [comment]
Status on November 15:
- We had 34 speakers on the website before COP (November 10).
- Since COP, 9 more speakers signed up. 
- Marketing ideas: write blog posts to introduce speakers, hold live events to interview them on specific topics, etc.

**Comment by holanita** [comment]
Updates:
- Checking with Tammy whether we can keep the next WG call on Dec 21 or we should continue in January?
- TBD next time: Developer Relations + new PMs

**Comment by holanita** [comment]
Status on January 18:
- We have 76 speakers listed on the website.
- Planning to add an event calendar and training materials.
- On hold but still receiving applications.

**Comment by holanita** [comment]
Status on February 15:
- Still on hold from PM perspective. 
- Current number of speakers: 82.
