### ISSUE TITLE
[Principles] Project update

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#31]
- [ ] Ontime
  - the consistency review will end on Thursday. If we don’t receive any more feedback or change requests via [Github](https://github.com/Green-Software-Foundation/training/issues/61) or [Slack](https://greensoftwarefdn.slack.com/archives/C02B4S0KS3U/p1662651870840389), we may close the review this week and submit the content to the LF next week so that they can create the course and quiz before COP. 

  - For the latest updates and status see the [last meeting agenda and minutes](https://github.com/Green-Software-Foundation/training/issues/67).

**Comment by holanita** [comment]
Status on November 15:
- We had 31 enrolled users from our project team and 7 of them passed the exam before COP (November 10).
- At the beginning of this week we had **223 enrolled users** and **44 have passed the exam** already.
- Marketing ideas: hold [small events](https://github.com/Green-Software-Foundation/training/issues/122), promote the course to  [org leads](https://github.com/Green-Software-Foundation/training/issues/103)

**Comment by holanita** [comment]
As discussed in the [Principles call today](https://github.com/Green-Software-Foundation/training/issues/128), we will talk about Marketing activities in the WG call to be held in January.

**Comment by holanita** [comment]
Status on January 18:
- Enrolled: 6857. Completed: 5541. Completion rate: 81%. Rating: 4.6/5.00.
- Meetings are on hold and will resume in March.
- We talked about various ideas for Earth Week e.g. Green Software Day.

**Comment by holanita** [comment]
Status on February 15:
- Enrolled: 10074. Completed: 8816. Completion rate: 82%. Rating: 4.6/5.00.
- The project remains on hold until the end of February from GSF PM perspective.
