### ISSUE TITLE
[Patterns] Project update

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#32]
- [ ] Help wanted – several pattern proposals have been added to [GitHub issues](https://github.com/Green-Software-Foundation/green-software-patterns/issues) recently. 

  - We are still waiting/looking for SMEs to contribute to the creation and review of patterns. Our plan for this week is to reach out to SMEs one by one. 
  - For the latest updates and status see the [last meeting agenda and minutes](https://github.com/Green-Software-Foundation/green-software-patterns/issues/51).

**Comment by holanita** [comment]
Status on November 15:
- We had published **40 patterns** before COP (November 10).
- We still have 40. Review process to be clarified before we add more. Each category should be owned by a lead.
- Marketing ideas: hold small events to promote AND explain patterns, promote the project to org leads (? TBD)

**Comment by holanita** [comment]
Status on January 18:
- We have 40 live patterns and around 20 more in review.
- Meetings are on hold and will resume with lower frequency.
- We discussed events such as a 'pattern party' for Earth Week, although this is not a priority in any way.

**Comment by holanita** [comment]
Status on February 15:
- The project remains on hold until the end of February from GSF PM perspective.
- OKRs to be discussed.
