### ISSUE TITLE
[Writers] Project Update

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#33]
- [ ] Forming the internal content team – first meeting today, working on defining the scope, roles, workflows and collaboration tools. 
  - We might use [GitHub](https://github.com/orgs/Green-Software-Foundation/projects/5/views/2) or the shared [publication queue document](https://docs.google.com/spreadsheets/d/1ATeQo_7v5zVW80gD05wZYRF2RrLQnW5HLAYr8VRMAEk/edit#gid=1729642952) for content management » TBD.

**Comment by seanmcilroy29** [comment]
@aecurrie 
https://www.oreilly.com/ has approached the GSF to potentially write a book on this space.
- [ ] Only 3 authors to be involved in this project

Anne to offer an update at the next WG meeting

**Comment by holanita** [comment]
@seanmcilroy29 @jawache do you have a due date in mind for the O'Reilly project?

**Comment by seanmcilroy29** [comment]
@holanita - @aecurrie is engaging with O'Reilly to establish what's need from the GSF side. 
At the next Community WG meeting, Anne is hopefully going to offer an update.

**Comment by jawache** [comment]
The book will take a year, we might explore publishing chapters as we go along. But this is a long term project, don't assume it's live. It needs a PR faq etc... first.

**Comment by holanita** [comment]
Status on November 15:
- **O'Reilly** TBD. See some details above. Discussed via email: we won't be able to call our book 101 Green Software
- We need a new process for the **Newsletter**. It will be published weekly form now on.
- The **Annual Report** will be due soon. Unsure if it should be considered a Community project or a Policy one?
- The **Magazine** has been on hold for several months because of COP. Shall we start now?
- **Translations** have been on hold since Nilooka left. 
- Do we need a new Project Lead for all of these? Who is driving blog posts, etc? Is it owned by Namrata now?

**Comment by holanita** [comment]
- newsletter - will be weekly from now on
- annual report - we have to do this soonish
- o'reilly - still to be discussed, Anne is working on this
- translations - need to quantify the value at some point (need to update website, upload content, etc)
- magazine - none of us were really involved at the beginning, TBD with Asim

**Comment by holanita** [comment]
As of January 18
- articles - will be managed by the GSF core team
- newsletter - sent weekly and managed by the GSF core team
- annual report - in progress and will be published at the end of January
- o'reilly - cancelled
- translations - on hold 
- magazine - on hold

**Comment by holanita** [comment]
To be discussed:
- our writer who is creating content at the moment, there is no project lead on this project since the summer of 2022
- we should provide our writer with some guidance / SME review and/or 
- we should try to recruit content creators in the community WG to help with content creation

**Comment by jawache** [comment]
Interestingly we're getting enough content to keep our blog site reasonably active so this isn't a "strong" priority for now. If there are no pieces of content for the blog from other sources he's going to create a write up of a podcast episode.

We should keep on the lookout for a volunteer who wants to lead/work with Urs on something more involved but until a person like that pops up our current process might actually work ok
