### ISSUE TITLE
Meeting invites for WG meetings

### ISSUE THREAD

**Issue by danielvaughan** [Green-Software-Foundation/community_wg#42]
**Is your feature request related to a problem? Please describe.**
Hi, I have missed a few meetings as I have just got an email saying starting now...

**Describe the solution you'd like**
Would it be possible to send our calendar invites for meetings in advance so I can get them blocked in my calendar please or add me if they are already sent.

**Describe alternatives you've considered**
I like the use of git but it does make things hard to track.

**Additional context**
. It would also be great if recordings were put on youtube etc. even if it is privately.

**Comment by seanmcilroy29** [comment]
Resolved
