### ISSUE TITLE
[Events/Meetup] Updates in 2023

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/community_wg#44]
In the next WG call, we should
- Discuss the Meetup project
- Discuss Earth Week. It would be great not to miss the opportunity from Meetup. Check [this](https://github.com/Green-Software-Foundation/learn/issues/142#issuecomment-1468360489) issue.
- Discuss again the possibility to sometimes have virtual events - this could take off some of the work pressure from organisers and could allow to have more events to keep the community active.

**Comment by holanita** [comment]
@tadanna reassigning this to you since you have taken over this project.

**Comment by tadanna** [comment]
I believe this is not relevant as the agenda of the next WG call needs to be updated on the specific issue - this is just a duplicate. Closing it.
