### ISSUE TITLE
2023-01-17.md

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#45]
# Community Agenda

Chair - Tammy McClellan – (MSFT)
Chair - Anne Currie - (Container Solutions)
Convenor - Sean Mcilroy – (LF)

## Date
2023-01-17 - 1630pm (BST) - [See your timezone](https://everytimezone.com/s/a8399b00)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
The Community Working Group Meeting is recorded and will be made available after the call

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call 
- [x] Approve agenda
> Sean reviews the agenda - Asim motions to agree - no objections - Agenda agreed
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/community_wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Meeting+Agenda%22)
> Asim motions to approve the previous meeting minutes - no objections - minutes approved

## Introduction 
- [x] New Community WG dedicated PM
> Anna introduces herself to the WG

## Meetup program
- [x] OKRs
- [x] Identify/decide the key tasks the launch the meetup program
- [x] Motion to agree on the roles we want GSF members to play in the meetup program vs non-GSF members.

> Asim outlines the proposed new Meetup program and how the new PM (Anna) will be leading activities to drive with community engagement

## Top level OKRs and GSF roadmap for 2023
- [x] Review and discuss WG OKRs

> Asim reviews and discusses the proposed OKR road map - https://github.com/Green-Software-Foundation/oc/discussions/5

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [x] #30
> Comments added to issue
  - [x] #31  
> Comments added to issue
  - [x] #32 
> Comments added to issue 
  - [x] #33 
> Comments added to issue

## Operation details / next steps: [Deferred to next meeting]

- [x] exact tasks, meeting frequency, communication channels

> Tammy to lead

## Next meeting  [Decision]
15 Feb

## AOB, Q&A
> Nothing added

## Adjourn 
> No objections meeting adjourned
-----------

### Action Item / Assigned to
- [ ] {notes to be added here}

**Comment by marcoshidalgonunes** [comment]
Attended

**Comment by holanita** [comment]
attended

**Comment by tadanna** [comment]
Attended

**Comment by markus-gsf-seidl** [comment]
Attended

**Comment by ccasher** [comment]
Attended

**Comment by jawache** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by ikolaxis** [comment]
Attended

**Comment by alex-kroll** [comment]
Attended

**Comment by subhasreej186** [comment]
attended

**Comment by VirginieCorraze** [comment]
attended
