### ISSUE TITLE
2023 05 10 - Community Working Group Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#57]
## Date
2023-05-10 - 16:00 GMT - See the time in your timezone https://everytimezone.com/s/a8399b00

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve Agenda
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/community-wg/issues/56)

## Discussions
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/52
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/54
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/58
- [x] Green Design Training  (UX) - Discussion topics

## Top-level OKRs and GSF roadmap for 2023 updates
- [x] Review and discuss WG OKRs 
  - [x] https://github.com/Green-Software-Foundation/oc/discussions/5
> Tammy to lead 

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] #30 
  - [ ] #31 
  - [ ] #32 OKRs to be discussed.
  - [ ] #33

## GSF Newsletter
- [ ] Submissions for the GSF newsletter 
> Submissions to Namrata

## Existing Action Items (Carried from 26-April)
- [x] Meetup: we will move away from Earth Day, @tadanna to get in touch with the meetup team to see if we can use their promotion offer later in June for the World Environment Day. @jawache to start a discussion in the community WG forum around what is needed for the date in June.
- [ ] WG to come up with prize categories for students for the next Hackathon and get people to sponsor those prizes
- [ ] Green software experts program: @jawache  to follow up on having someone coming in to discuss how MVP is managed
- [ ] Writers project: there is a [writer repo](https://github.com/Green-Software-Foundation/writers) where everybody can add New Article Proposals.
- [ ] Internal advocacy: @jawache and @tmcclell to start a discussion topic about this 

## New Action Items 
- [x] Adam looking at Meetup Groups Merging
- [ ] Potential GSF 2nd Anniversary meetup alignment - 25th May (London, UBS event, currently scheduled 18th May)
- [ ] World Environment Day, possibility to align podcast and use as livestream, Adam to follow up
- [ ] Adam to create subgroup meeting for above activity
- [x] Adam to look at Exams with Sean
- [ ] Adam to look at standard set of slides, plus selection of presentations from speakers who are happy to share
- [ ] Adam to look at long term speaker resource page
- [x] Adam looking at tracking mechanism for third-party communities, likely to be manual
- [x] Speaker tracking/feedback tool - Adam to create. 

## Next meeting  [Decision]
24-May-2023

## AOB
- [x] Member questions or topic submissions?

## Adjourn 
- [x] Motion to adjourn

**Comment by adamj89** [comment]
3P Meetup Tracking: https://github.com/orgs/Green-Software-Foundation/projects/20/views/5

**Comment by tholewis** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by jawache** [comment]
Attended

**Comment by adamj89** [comment]
attended

**Comment by greenhsu123** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by alex-kroll** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended the last 20 min
