### ISSUE TITLE
Move CWG meeting to Zoom 

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#70]
### Discussed in https://github.com/Green-Software-Foundation/community-wg/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **adamj89** June  7, 2023</sup>
Does this community prefer Google Meet or Zoom (or another platform)</div>

- [x] Can we have a CWG license rather than individual (@adamj89 to investigate)--- not viable

**Comment by adamj89** [comment]
Zoom now has a 'join before host' function.

**Comment by adamj89** [comment]
Issue is currently blocked due to license allocation. Hope to fix for the next meeting!

**Comment by adamj89** [comment]
@seanmcilroy29 can I pick this up with you?

**Comment by greenhsu123** [comment]
Zoom please! We have been advised to stop using Google Meet.

**Comment by adamj89** [comment]
There was already a vote carried to do the move so this will happen once sorted @greenhsu123 - I am hoping by the new year :)

**Comment by seanmcilroy29** [comment]
@adamj89 - The meeting link has been updated to Zoom and will automatically record the meeting.
Once the meeting recording has been processed, you'll receive the details.
