### ISSUE TITLE
PARKED: Request to begin posting on Mastodon / fediverse

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/community_wg#73]
Request for @NAMRATA-WOKE to include https://joinmastodon.org/ in our social media strategy.

Proposed steps:
- [ ] Create an account at a suitable federated server - such as https://fosstodon.org/
- [ ] Add the new Account to the location field on Twitter/X to make sure the account is discoverable
- [ ] Add a lookup link to the source code in the header of https://greensoftware.foundation such as:
```
<!-- Mastodon, because of Twitter/X -->
<link href="[https://fosstodon.org/@gsf](view-source:https://fosstodon.org/@gsf)" rel="me">
```
- [ ] Add the [https://greensoftware.foundation](https://greensoftware.foundation) website to the profile metadata at https://fosstodon.org/settings/profile **after** adding the lookup link so that the website is marked as verified ![image](https://github.com/Green-Software-Foundation/community-wg/assets/19361656/9ffe4f62-d79d-42d7-b399-e5daf7102843) e.g.:
![image](https://github.com/Green-Software-Foundation/community-wg/assets/19361656/3edc40e9-dd28-4a4b-9bc9-31a33147354e)
- [ ] Begin posting on Mastodon with the same content as X/Twitter, or using Mastodon as primary and recirculating to Twitter

**Context:**
- Significant adoption of alternatives to Twitter/X
- Supports Threads if Threads becomes federated
- Open Source alternative to Twitter/X
- Minimal overhead if replicating same tweets/posts

**Comment by adamj89** [comment]
@Sealjay I have 2 questions (perhaps for @NAMRATA-WOKE to input on)
1 - Do we have any evidence there is a critical mass of SW practitioners on Mastodon? I see little activity browsing myself, and the system is not optimised for organisations. 
2 - Are there any available tools to simplify cross-social posting? I would like us to think about what we could post to Instagram in addition to the existing platforms but different formatting is required vs. Twitter. 
3 - We also have an inactive page on Facebook which we should review as part of this conversation.

**Comment by adamj89** [comment]
@Sealjay I will add this to the agenda for the upcoming Community WG. Would you be able to attend?

**Comment by Sealjay** [comment]
> @Sealjay I have 2 questions (perhaps for @NAMRATA-WOKE to input on) 1 - Do we have any evidence there is a critical mass of SW practitioners on Mastodon? I see little activity browsing myself, and the system is not optimised for organisations. 2 - Are there any available tools to simplify cross-social posting? I would like us to think about what we could post to Instagram in addition to the existing platforms but different formatting is required vs. Twitter. 3 - We also have an inactive page on Facebook which we should review as part of this conversation.

It might relate to the Mastodon org you're in! One difference to X/Twitter is that discovery begins with the Mastodon server you join, and I'm seeing a significant amount of Software Practitioners in mine (FOSStodon) - I'm happy to screenshare.

For Mastodon, we could cross-post the same content.

**Comment by adamj89** [comment]
Cool, that sounds good. I am not active on FOSStodon (yet)

**Comment by Sealjay** [comment]
Tagging @Willmish

**Comment by Willmish** [comment]
+1 on this, I myself wanted to reactivate my Twitter (X), but after recently participating at Embedded Open Source Summit in Prague, I noticed that more speakers are also sharing their Mastodon profiles, and am finding them on the platform afterwards.

Im not on FOSStodon but Universeodon, but maybe worth switching if there are more Software folks there. Either way wanted to jump in that I'd be supportive of having a GSF account on an open source social media platform like Mastodon :)

**Comment by adamj89** [comment]
@Willmish thank you for your feedback in the meeting

@NAMRATA-WOKE referenced the volume of work involved in adding additional social platforms and the impact on strategy. 

Disadvantages
- Community Size
- Difficulty of cross-server visibility?
- Difficulty of brand visibility vs. individual a/c

Advantages
- Vibrant OSS community


Questions
- Strategic direction
- What do we want to post

@tmcclell has asked @NAMRATA-WOKE to do a research on this topic and come back with answers.

**Comment by Willmish** [comment]
Btw Zephyr Project, a fellow Linux Foundation organisation is on mastodon [@zephyr@social.lfx.dev](https://social.lfx.dev/@zephyr). Also [@linuxfoundation@social.lfx.dev](https://social.lfx.dev/@linuxfoundation), so guessing social.lfx.dev is a Linux foundation domain and server ?

**Comment by adamj89** [comment]
Feedback from 16 August call

-- Volunteer CM for mastodon?
-- Questions as to who is really active in our community
-- Need to discuss w/ @NAMRATA-WOKE @jawache

**Comment by adamj89** [comment]
Namrata yet to discuss this with Asim. Anne suggests connecting with Chris Adams who is passionate about Mastodon. 
Namrata is keen that any activity is community driven rather than driven by GSF Marketing. 

@adamj89 @jawache @NAMRATA-WOKE to have discussion.

**Comment by adamj89** [comment]
Tagging @mrchrisadams here too.

**Comment by mrchrisadams** [comment]
LOL, I'm passionate about Mastodon? I use it, but I'm not sure I'd say I'm passionate about it 😄 

I agree there's been a movement of techie types to Mastodon more than other accounts, but not every instance accomodates corporate accounts or project accounts, and I don't think it's really geared up businesses to use the same way Twitter was. 

There's also a few instances to choose from.

Hachyderm is about the same size as Fosstodon for example, and a few of my more technical friends use it. 

More below:
https://hachyderm.io/about
https://community.hachyderm.io/about/

There a number of well liked company accounts hosted on it, like Tailscale and Oxide Computing, but there are a bunch of rules they've agreed to follow to be invited there:
https://community.hachyderm.io/approved

If it helps, where I work at the Green Web Foundation we haven't committed to any federated social media yet - just keeping on top of LinkedIn is enough already!

I don't have too much more to add right now, but I hope that provides some extra context.

**Comment by adamj89** [comment]
Thanks @mrchrisadams! You were mentioned by name in the CWG call 🤩

This is really helpful.

**Comment by jawache** [comment]
Our social media strategy is automated, so if this is something that can easily be added to the tooling we use (i.e. it supports mastodon as a target same as LI/TW) I don't see a problem with it. But let's not add a manual process to @NAMRATA-WOKE's plate there is already a lot on there than just social media posting which we've mostly automated.

**Comment by tmcclell** [comment]
The WG decision was to encourage practitioners to contribute to the Mastodon. We can certainly automate updates, but the value may not be there - with the right kind of conversations and engagements. We recommend and encourage GitHub discussions for insightful conversations. If there is a strong push for presence in Mastodon - it should be Community WG led with GSF support.

**Comment by adamj89** [comment]
Thank you @tmcclell 
On the basis of this discussion and current capacity, I am keeping this issue open but moving it down the agenda for now.

**Comment by adamj89** [comment]
Closing as this will now be considered as part of the Comms exec project.
