### ISSUE TITLE
EPAM - join CWG to talk about Internal Green Advocacy

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#78]
Linked to member check-in https://github.com/Green-Software-Foundation/gsf-admin/issues/299 (sorry, access to that repo for GSF staff only!)

Suggestion for EPAM to come and talk about their internal Green Software community and their use of Principles and patters.

Suggestion for 2023-10-25 CWG meeting? @cm-howard

**Comment by cm-howard** [comment]
Very happy to support this and looking forward to discussing further.

**Comment by adamj89** [comment]
@cm-howard as discussed, after Decarb would you be OK to pop into one of our CWG meetings (late Nov/early Dec) to give us the inside scoop?

Cc @russelltrow

**Comment by cm-howard** [comment]
100%  - please count me in to support on this! @adamj89 @russelltrow

**Comment by russelltrow** [comment]
The WG decided to pause featured member slots for the time being and explore how we could bring the insights to a wider audience.
