### ISSUE TITLE
2023 09 13 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#80]
## Date
2023-09-13 - 3pm UTC - See the time in your timezone https://everytimezone.com/s/cc45bdd5

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available. Please review the [Linux Foundation privacy policy](https://www.linuxfoundation.org/legal/privacy-policy)

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/community-wg/issues/79)
- [x] OKR & KPI updates
- [x] https://github.com/Green-Software-Foundation/community-wg/issues/73
- [x] https://github.com/Green-Software-Foundation/oc/issues/46
- [ ] https://github.com/Green-Software-Foundation/community-wg/issues/81
- [ ] Discussion [Green Software Verified Facts](https://github.com/orgs/Green-Software-Foundation/discussions/47)
- [ ] Reviewing open [Oversight Committee issues](https://github.com/Green-Software-Foundation/oc/issues?q=is%3Aissue+is%3Aopen+label%3A%22Community+WG%22)
- [ ] Newsletter call for content
- [ ] Any Other Business and Q&A
- [ ] Motion to adjourn

## Upcoming moments in time
- [ ] 16 November 2023 - Decarbonize Software 
- [ ] 30 Nov – 12 Dec 2023 - COP
- [ ] Q4 2023 - Launch Contributors Programme, Initial Experts announced
- [ ] 2024 Q1 - Formal launch of Experts Programme
- [ ] 2024 Q1 - Impact Engine Hackathon

## Any Other Business
- [ ] Member questions or topic submissions?

### Champions program
* Can we nominate experts after the program launches?

### Green Software Maturity Matrix
* @tmcclell shared https://learn.microsoft.com/en-gb/assessments/f236012a-0070-45db-b94c-fe8de0799f38/

## Decisions
- [ ] Park Mastadon for the time being https://github.com/Green-Software-Foundation/community-wg/issues/73 

## Action Items
- [ ] @NAMRATA-WOKE to report the ratio of Decarb signup - Member Orgs vs General Public
- [ ] @russelltrow meet with @aecurrie to discuss the GSMM and relationship to GSF

**Comment by russelltrow** [comment]
In the last meeting I agreed to find out the most popular courses’ uptakes from LF and report back to the group:

1. Certified Kubernetes Administrator
2. Kubernetes Fundamentals
3. Certified Kubernetes Application Developer
4. Green Software Practitioner
5. Linux Kernel Development

**Comment by Sealjay** [comment]
Request to add https://github.com/Green-Software-Foundation/community-wg/issues/81 to a future call.

**Comment by tholewis** [comment]
Attended.

**Comment by yuxin1234** [comment]
Attended.

**Comment by greenhsu123** [comment]
Attended.

**Comment by Willmish** [comment]
Request to add #83 to the next community wg call :)
