### ISSUE TITLE
Suggest adding Giscus to articles on greensoftware.foundation

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/community_wg#81]
**Is your feature request related to a problem? Please describe.**
Not related to a problem; but a suggestion to increase and generate new community discussions.

**Describe the solution you'd like**

I would like all articles on https://greensoftware.foundation/articles to have Giscus embedded. https://giscus.app/

Giscus allows for users logged in via GitHub to leave comments on pages with their GitHub username.

This ensures users are logged in and verified; and also generates new comments for the weekly digest.

This will direct further users to GitHub discussions.

**Describe alternatives you've considered**
- Proprietary comment systems
- Not having comments (status quo)
- Disqus

**Additional context**

I considered this on other pages, or the subdomains for the working groups; I do think this would be beneficial, but the URLs and layouts are so varied, starting with articles sounds like it would generate the most engagement.

**Comment by adamj89** [comment]
@NAMRATA-WOKE

**Comment by tmcclell** [comment]
@Sealjay  - who would manage the work to add the giscus and would it devalue other features like discussions? What kind of guardrails for spam, etc could we take advantage of.

**Comment by Sealjay** [comment]
> @Sealjay - who would manage the work to add the giscus and would it devalue other features like discussions? What kind of guardrails for spam, etc could we take advantage of.

@tmcclell  - I'm happy to help, but I'm not sure who manages the current site - I assumed @NAMRATA-WOKE - takes about 120 seconds to install and setup.

All of the conversations are actually stored in GitHub Discussions - so it should drive more people to discussions, and has all of the same guardrails.

Here is a screenshot of it in use on a webpage:
![image](https://github.com/Green-Software-Foundation/community-wg/assets/19361656/f4ebc544-9aca-4011-b006-0f2e5c98a108)

But the content is actually created in GitHub Discussions:
![image](https://github.com/Green-Software-Foundation/community-wg/assets/19361656/b279fb7c-00bb-4111-aec0-cf822f8c46ca)

**Comment by adamj89** [comment]
Could we give access only to GSF Champions/Members as a pilot?
@russelltrow thinks not. 
Permissions control?

**Comment by adamj89** [comment]
Comment from Thomas Lewis : why would we not use GSF Discussions for this?

**Comment by adamj89** [comment]
Decision to close this for now in favour of pursuing GSF Discussions

**Comment by adamj89** [comment]
Decision to close this for now in favour of persuing GSF Discussions
