### ISSUE TITLE
[Agenda Item]: Consider supporting ClimateHack 2023 (co-organised by UCL's AI Society)

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/community_wg#83]
University College London's AI Society is co-organising this years ClimateHack hackathon, quoted from [Society's website](https://uclaisociety.co.uk/our-initiatives/#-climatehackai-2023):

> [ClimateHack.AI 2023](https://climatehack.ai/) is a second edition of a joint student initiative uniting the AI communities of 25 world-leading UK, US and Canadian universities to launch an ambitious AI competition to help cut carbon emissions in the energy sector by up to 100,000 tonnes a year! We are proud to host ClimateHack.AI 2023 on [DOXA](https://doxaai.com/) - an AI competition platform that originated in our society!

The goals of the hackathon are aligned with the core vision of GSF, so it seems logical for us to get involved, given the fact that GSF is getting more active in the area of Academia, and Universities joining GSF as member organisations.
The AI Society is seeking financial support for the event, as well as mentor / speaker support.

@TheRootOf3 @jeremylo are representatives of the UCL AI Society who I'd like to invite for next Community WG call and can fill in more details about the event, its goals, organisers and support seeked. Please feel free to add any more info under this issue

**Comment by adamj89** [comment]
@TheRootOf3 @jeremylo good to meet you

Are there proposed dates aligned for this? Sorry if I've missed it.

**Comment by TheRootOf3** [comment]
Hi @adamj89, great to meet you as well! Thank you for your interest in ClimateHack.AI 2023! 🌍

The competition is split in 2 parts:
- Online qualification round beginning in the middle of November 2023 until the middle of January 2024,
- In-person finals happening during a weekend in the middle of February 2024, lasting 2/3 days.

We're looking forward to telling you and the GSF community more about our plans and the challenge! 🌱

**Comment by adamj89** [comment]
Thanks @TheRootOf3. I don't suppose you could make it this week? We have the meeting at 4PM UK time on Wednesday. We would have maximum 10-12 mins to spend on this topic. Otherwise in 2 weeks time?

**Comment by TheRootOf3** [comment]
Together with @jeremylo, we are more than happy to join you this Wednesday! 🎉

**Comment by adamj89** [comment]
Action is @adamj89 to follow up with member orgs and LF to identify source of funding. @NAMRATA-WOKE will also connect regarding Marketing/Comms connection. 
Next connection in 1 week

**Comment by adamj89** [comment]
£10-15k GBP

**Comment by tmcclell** [comment]
@NAMRATA-WOKE to sync up with @adamj89 to determine if GSF would contribute. End of next week. Sarah brought up reusability with other universities. @NAMRATA-WOKE having internal discussions with budget strategy. @aecurrie pointed out we have a lot of content available on the GSF website that we can point students to. Thomas says that MSFT is working on course curriculum that will be open source based on GSF materials. @NAMRATA-WOKE asked that we create a discussion on GitHub for it. @Willmish to create discussion - thanks!!

**Comment by Willmish** [comment]
> @NAMRATA-WOKE to sync up with @adamj89 to determine if GSF would contribute. End of next week. Sarah brought up reusability with other universities. @NAMRATA-WOKE having internal discussions with budget strategy. @aecurrie pointed out we have a lot of content available on the GSF website that we can point students to. Thomas says that MSFT is working on course curriculum that will be open source based on GSF materials. @NAMRATA-WOKE asked that we create a discussion on GitHub for it. @Willmish to create discussion - thanks!!

Here is the discussion link, please add any details of conversation topics I might have missed: https://github.com/orgs/Green-Software-Foundation/discussions/72

**Comment by russelltrow** [comment]
@adamj89 @NAMRATA-WOKE @Willmish has everything here been actioned? 

What conclusion did you come to with @TheRootOf3 @jeremylo?
