### ISSUE TITLE
[Project Proposal] Higher Education strategy

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#89]
@tholewis, @PindyBhullar & @adamj89 to draft their thoughts on how the GSF might engage with Higher Education institutes.

Originally [discussed here](https://github.com/orgs/Green-Software-Foundation/discussions/72) and then agreed in the [Community WG meeting](https://github.com/Green-Software-Foundation/community-wg/issues/88) on 25 October 2023.

Ideally present back to CWG on 22 November.

**Comment by tholewis** [comment]
Apologies for the delay on this. We have a first draft completed which is going through another round of iteration. We will then present it to the Community WG at the January 31st meeting for review and how/if we want to move forward.

**Comment by russelltrow** [comment]
Hey @tholewis when would you like to raise this at the CWG?

**Comment by tholewis** [comment]
Hi @russelltrow, let's raise it at this week's meeting! Thanks for supporting me during some challenging weeks!

**Comment by tholewis** [comment]
[University Learning Proposal v.0.1.pdf](https://github.com/Green-Software-Foundation/community-wg/files/14273025/University.Learning.Proposal.v.0.1.pdf)

Hi everyone, here is a .pdf version of the University Learning Proposal. Wanted to use this document to kickstart the conversation around it. Will use some of the time during the Working Group meeting tomorrow to briefly run through it, discuss next steps (process, timeline, etc.), and then use [this open issue](https://github.com/Green-Software-Foundation/community-wg/issues/89) to have further discussion to prepare for the next iteration by the next working group meeting.

**Comment by tholewis** [comment]
Thank you in advance to everyone helping to support the University Learning Proposal! For those who were at the Community Working Group meeting, we discussed the document and I had mentioned a few key areas and questions we would love people's feedback on:

- **Design considerations.** As these will help provide scope and guidance, do they sound reasonable to you? Should we add any additional guidelines to our approach and planning?
- **Needs assessment.** Are there any questions you feel need to be a part of it? We do want to balance not overwhelming them with questions as they are busy, but also that we have the precise questions to help move us forward. Do you have higher learning institutions you have contacts with that you would like us to discuss this with?
- **Proposed activities.** Are there activities you would prioritize? When we put the timeline together along with contributors, we will focus on these in the first milestones.
- **Overall.** Is there anything big we are missing here? 

Please feel free to add your feedback in this Github Open Issue or as a comment in the document once we have a final home for it and we can track changes. At the next Community WG meeting, we will provide an update to the document and lay out a timeline and start the Needs Assessment discussion with higher education learning institutions that are members of the GSF. 🌳

**Comment by russelltrow** [comment]
@tholewis it looks like you had a fantastic discussion. 

Shall I raise a Motion so that the CWG can officially approve the project and the GSF can give you a final home?

**Comment by tholewis** [comment]
@russelltrow - Apologies for my delayed response. Although I haven't had much feedback within this open issue, I've gotten good feedback ad hoc and within our Community Working Group meetings. So, if it does make sense that we propose it as a proper project, that would be great or if there are any concerns we can be sure to address those first and then move forward. It looks like the discussion is on the table for tomorrow so that we can discuss next steps!

**Comment by tholewis** [comment]
For the 2024-02-28 Community WG meeting regarding this topic, I think I'd like to cover the following:

1. The next step is to start with the Needs Assessment. I can put together an e-mail that can be sent to our university and learning institution members. Who can help me reach out to them?
2. I just got good feedback that we should also reach out to Student programs at the big hyperscalers. I know the leads for the Microsoft and Google student programs, but does someone know who it is for AWS and perhaps can introduce us? 
3. As @russelltrow mentions above, would like to know if we can go ahead and propose that we move ahead with the project and can make sure that it is set up for contribution and execution.
4. If we move to project, who would like to be a part of the core team? If you are familiar with the RACI model, this would be folks in the R (responsible) role (e.g. This person is responsible for performing the task or completing the work. They are the ones who actually do the work.).

**Comment by russelltrow** [comment]
Sounds perfect @tholewis, the next formal step will be raising a [new project proposal](https://github.com/Green-Software-Foundation/oc/issues/new?assignees=tmcclell%2C+Sealjay%2C+seanmcilroy29&labels=project%2C+proposed&projects=&template=new-project-proposal.md&title=%5BProject%5D+Title+Of+Project)

**Comment by russelltrow** [comment]
Hey @tholewis can I provide any support with raising the project proposal?

**Comment by tholewis** [comment]
@russelltrow  Apologies, been out of office for an event all this week. On Monday, I have some time allotted to jump back into this and will follow up with you on this as I'd love to make sure that I get the project proposal correct and get a project place on GitHub to start sharing everything and collaborating.

**Comment by tholewis** [comment]
Here's a quick update for this week. 🌳

Regarding the University Plan, I am back from vacation and various life/work blockers, so I have time to focus on the University Plan. The current status is:

1. I will fill out the [New Project Plan](https://github.com/Green-Software-Foundation/projects/issues/new?assignees=tmcclell%2C+Sealjay%2C+seanmcilroy29&labels=project%2C+proposed&projects=&template=new-project-proposal.md&title=%5BProject%5D+Title+Of+Project) and get it submitted.
2. We are now ready for the Needs Assessment meetings with higher education institutions as per the document. I will work with Namrata to get those scheduled and get them kickstarted.
3. Meeting with Russ early next week to work on the activities we need to get kicked off as a part of the project and set up a recurring meeting for the project itself.
4. Will continue to update and refine the document and upload a new version [here](https://github.com/Green-Software-Foundation/community-wg/issues/89) or when we create a project space we can place it there.

Thank you for everyone's patience and look forward to working with everyone to create a great experience for higher education institutions engaging with the GSF!
