### ISSUE TITLE
2023-11-22 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#91]
## Date
2023-11-22 - 16:00 UTC - See the time in your timezone https://everytimezone.com/s/89004c46

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available. Please review the [Linux Foundation privacy policy](https://www.linuxfoundation.org/legal/privacy-policy)

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [ ] Review Past Meeting Actions & Approve Minutes https://github.com/Green-Software-Foundation/community-wg/issues/90
- [ ] OKR & KPI update (see below)
- [ ] @NAMRATA-WOKE Member Check-in Report
- [ ] Recap of the [GSF Project Tracker](https://airtable.com/appVPOiFrCIjAAcvB/shr7sf6OVz6I9gL3L)
- [ ] https://github.com/Green-Software-Foundation/green-software-maturity-matrix review
  - [ ] Any additional joiners?
  - [ ] How shall we engage with Member Organisations?
- [ ] Decarb washup
- [ ] Reviewing open [Oversight Committee issues](https://github.com/Green-Software-Foundation/oc/issues?q=is%3Aissue+is%3Aopen+label%3A%22Community+WG%22)
- [ ] AOB, Q&A & Adjourn (5mins)

## Past Meeting

* https://github.com/Green-Software-Foundation/community-wg/issues/90 (notes to be reviewed)

## OKRs & KPIs

* Patterns
  * 50 Patterns live
  * 48 GitHub stars
* Principles
  * 65,364 enrolments / 100,000
  * 54,102 completions
* Decarb
  * 2,032 sign-ups  / 2,000
  * 2,242 views
  * 391 Comments/350
* Champions
  * 251 contributions in the last month / 100
  * 57 people adding new contributions per month / 10
* Meetup
  * 6,789 Members / 10,000

## Upcoming moments in time

* ~16 November 2023 - Decarbonize Software~
* ~16 November 2023 - Launch Champions programme~
* 30 Nov – 12 Dec 2023 - COP
* 26 Feb - 15 March 2024 - ~Carbon~ *Impact*Hack 24
* Q1 2024 - Formal launch of Experts Programme
* Q2 2024 - Summit (June)

## Any Other Business
- [ ] ...

## Decisions
- [ ] ...

## Action Items
- [ ] ...

**Comment by alexander-kroll** [comment]
Attended

**Comment by adamj89** [comment]
Quorum not met, carrying over most actions

**Comment by adamj89** [comment]
Closed as meeting did not go ahead as planned.
