### ISSUE TITLE
[Agenda Item] Engagement across regions

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/community_wg#93]
**Overview**:
> Are there any ways we can increase engagement in new geographies?

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [ ] Governance: Other
- [ ] Process
- [x] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [x] Community
- [x] Open Source
- [x] Policy
- [x] Standards
- [x] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. Green-Software-Foundation/oc#10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Could we run shorter 15 minute sessions for say asia pacific, or ask people to input into the agenda beforehand?

**Comment by Sealjay** [comment]
Main thing I’m thinking was to run short meetings for the area with less engagement, e.g. Asia pacific/europe timezones, the day before or after
Let the bulk of people dictate the biggest meeting

**Comment by tmcclell** [comment]
@jawache new form where we asked members where they are based (timezone).

**Comment by jawache** [comment]
This has been added to the new onboarding form so this issue can be closed: https://greensoftware.foundation/onboarding/

**Comment by tmcclell** [comment]
@adamj89 - Recommends additional meet up groups - review gaps and recommendations with new project manager.

**Comment by adamj89** [comment]
Closing as this is forming part of the 2024 Exec Program for Meetup
