### ISSUE TITLE
[Agenda Item] Tracking of public speaking engagements

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/community_wg#95]
**Overview**:
How do we track public speaker engagements ? (E.g. a form speakers to submit to?) And how can we visualise that? (e.g. collect all speaker engagements as a calendar on https://speakers.greensoftware.foundation/

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [ ] Governance: Other
- [x] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [x] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [ ] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. Green-Software-Foundation/oc#10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by NAMRATA-WOKE** [comment]
@Willmish @Sealjay 

We currently have a [Google form](https://docs.google.com/forms/d/e/1FAIpQLScdlrF3-6IRQt-5mGELyxHeNgwUvnQFmRiuBze4jow7gd7y9g/viewform?usp=sf_link) that we share in every single newsletter, encouraging speakers to submit past and upcoming talks on green software. 

I have an [Events Tracker](https://docs.google.com/spreadsheets/d/1mKEBxZxDcBfgu-ccGQg7amwV97wmMCFxhmp2MXSK-rg/edit?usp=sharing) that I manage, and include as much information as possible. It's still mostly pulling information from people/the internet. Ideally we can get to a place where folks are pushing information to us! 

@jawache remember we talked about having an events section on the website? I think this would pull traffic to the site and be a good place for people to keep up to date with the latest talks. It will also further incentivize folks to share their upcoming talks with us. Once SOGS is out the door, perhaps we can revisit this with Osama?

**Comment by adamj89** [comment]
It would be great to understand a rough number of people reached by speakers as well.

**Comment by tmcclell** [comment]
@jawache - What's the incentive for reporting the speaking of conferences. @Sealjay  asked what the process was for letting folks know. @Willmish - recognize through socials and speakers bureau, @adamj89  - Not seeing contributions - directory of GSF contributions/experts - dynamic. Something that can be self updated. @Sealjay should be easy to view. Sarah - how do folks find people now and also folks use Linked In or other means to get a speaker. @mrchrisadams Questions on who is speaking and where (data?) through Google forms Sarah - items for newsletter - asking folks to share. @mrchrisadams how to find experts and level of expertise with vetting. @jawache - Propose we let Adam become the project lead to present solution and get feedback from Community WG. Work out what's feasible in what time frame, launched in stages? @Sealjay - how do we grow experts? Proposed in 2 WGs.

**Comment by adamj89** [comment]
Closing as this forms part of Champions, badges slated for phase 2.
