### ISSUE TITLE
Indeed would like to donate a green software rubric to the CWG

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#97]
# Context

In the [2023 12 06 - Green Software Community Working Group](https://github.com/Green-Software-Foundation/community-wg/issues/96) @moin-oss from Indeed shared details of a project that they are considering donating to the Green Software Foundation.

* A rubrics project intended to be a set of guides that developers can follow to make their products more sustainable
  * The goal is to have a set of rubrics, along with guides, that are tailored to specific types of development
  * The plan is to create rubrics that list actions that developers can take within each category and categorize them by developer effort (low, medium, high)
* Still at a prototype stage
  *  Has been challenging to get adoption
* Believe there is lots of alignment with the current Patterns, Principles & Maturity Matrix projects
* He would like to donate the project so that
  * There can be contribution from different organisations - Get input from others
  * See the project get into a state when it can be more easily adopted
* They would like to continue leading the project if/when the project it is donated

# References

* https://github.com/Green-Software-Foundation/oc/issues/78

# Actions

- [x] @russelltrow organise a call between @moin-oss and @aecurrie 
- [x] @Sophietn share GSF project donation process
- [ ] @moin-oss raise project donation issue
- [ ] Review donation issue in 14 Feb 2024 CWG meeting
- [ ] Raise CWG motion to approve/reject project donation

**Comment by Sophietn** [comment]
Sharing the [GSF Project Donation Process here](https://oc.greensoftware.foundation/project-donations.html)

**Comment by russelltrow** [comment]
@aecurrie, @moin-oss and I met on 26th January and came to the following conclusions:

* Agreed that the Rubric should be its own GSF project. It appears to sit between the Patterns, Maturity Matrix and potentially OUSE.
* Mohammad will be Project Lead.
* Mohammad will start the Donation process
* Aim to have the donation proposal reviewed & approved in the February 14th Community Working Group meeting

**Comment by NAMRATA-WOKE** [comment]
Hey @Sophietn I believe this is moving forward so if you'd like to update the issue, feel free. Just noticed there was an issue for this work!

**Comment by moin-oss** [comment]
I have opened a project donation issue here: https://github.com/Green-Software-Foundation/oc/issues/78

**Comment by Sophietn** [comment]
Thank you @NAMRATA-WOKE and @moin-oss. I have added detail and the process for next steps to the [Project donation proposal issue. ](https://github.com/Green-Software-Foundation/oc/issues/78#issuecomment-1934336718). 

We're currently at this step
- Community Working Group to discuss the donation and pass a motion to approve or reject Indeed's proposal to donate the project to the GSF.

I will converse with @russelltrow to ensure this is an [Agenda item](https://github.com/Green-Software-Foundation/community-wg/issues/97) at Community Working Group call in the near future.

**Comment by russelltrow** [comment]
@PindyBhullar @moin-oss I see from the last CWG that you planned further discussions about the playbook.

In the meeting was their enough discussion on the project donation therefore I can officially raise a Motion for the CWG to  approve the donation or do you need further discussion before I do that?

**Comment by moin-oss** [comment]
Hey @russelltrow , I haven't discussed this with @PindyBhullar yet.  At the meeting I did bring up this project and requested feedback on it, but there wasn't much discussion during the meeting itself.  I'm not sure if that's sufficient to move it forward or not.

**Comment by russelltrow** [comment]
Closing this issue as we have now progressed to the project approval stage
