### ISSUE TITLE
2023-12-20 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#99]
## Date
2023-12-20 - 16:00 UTC - See the time in your timezone https://everytimezone.com/s/89004c46

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF Working Group meetings are recorded, transcribed and will be made available to members of the Green Software Foundation. If you object to recordings for whatever reason, please do not participate in the meeting and contact the PM @adamj89. Please review the [Linux Foundation privacy policy](https://www.linuxfoundation.org/legal/privacy-policy)

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] We are on Zoom! Overview of recording policy.
- [ ] Review Meeting Notices (see above)
- [ ] Review Past Meeting Actions & Approve Minutes https://github.com/Green-Software-Foundation/community-wg/issues/96 
- [x] OKR & KPI update (see below)
- [x] Carbon Hack overview
- [x] Festive Fun 🤩
- [x] @NAMRATA-WOKE Member Check-in Report
- [x] Review of the [GSF Project Tracker](https://grnsft.org/Projects/CWG)
- [ ] AOB, Q&A & Adjourn (5mins)

## Past Meeting

* https://github.com/Green-Software-Foundation/community-wg/issues/96 (notes to be reviewed) (from 2 meetings ago, last meeting did not meet quorum)

## OKRs & KPIs

* Patterns
  * 50 Patterns live
  * +1 backlinks
* Principles
  * 67,632 enrolments / 100,000
  * 55,705 completions
* Decarb
  * 2,032 sign-ups  / 2,000
  * 2,407 views
  * 391 Comments/350
* Champions
  * 343 contributions in the last month / 100
  * 68 people adding new contributions per month / 10
* Meetup
  * Over 7000 Members / 10,000
* Carbon Hack
  * TBC

## Upcoming moments in time

* 26 Feb - 15 March 2024 - CarbonHack 24
* Q1/Q2 2024 - Launch of Experts Programme
* Q2 2024 - Summit (June)

## Any Other Business
- [ ] ...

## Decisions
- [ ] ...

## Action Items
- [ ] ...

**Comment by PindyBhullar** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by russelltrow** [comment]
Attended
